import "/styles/globals.css";
import { FC, PropsWithChildren, ReactElement } from "react";
import { NextPage } from "next";
import Head from "next/head";
import type { AppProps } from "next/app";

export type NextPageWithLayout<P = {}, IP = P> = NextPage<
  P & { section: string },
  IP
> & {
  Layout: FC;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};

export default function App({ Component, pageProps }: AppPropsWithLayout) {
  const Layout =
    Component.Layout ?? (({ children }: PropsWithChildren) => children);

  return (
    <>
      <Head>
        <title>Movies Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout {...pageProps}>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}
